CC = g++
CXXF = -std=c++20
LDF = -lstdc++

all: Builder
Builder: main.o card.o Deck.o Player.o CardManager.o
	 $(CC) main.o card.o Deck.o Player.o CardManager.o -o Builder $(LDF)

main.o: main.cpp
	$(CC) -c main.cpp $(CXXF)

card.o: card.cpp
	$(CC) -c card.cpp $(CXXF)

Deck.o: Deck.cpp
	$(CC) -c Deck.cpp $(CXXF)
	
Player.o: Player.cpp
	$(CC) -c Player.cpp $(CXXF)
	
CardManager.o: CardManager.cpp
	$(CC) -c CardManager.cpp $(CXXF)