CC = g++
CXXF = -std=c++14
LDF = -lstdc++

all: Builder
Builder: main.o card.o Deck.o
	 $(CC) main.o card.o Deck.o -o Builder $(LDF)

main.o: main.cpp
	$(CC) -c main.cpp $(CXXF)

card.o: card.cpp
	$(CC) -c card.cpp $(CXXF)

Deck.o: Deck.cpp
	$(CC) -c Deck.cpp $(CXXF)